### ISSUE TITLE
ENSO can't find ORCA

### ISSUE THREAD

**Issue by HenriqueCSJ** [grimme-lab/enso#10]
I'm on python 3.8
It looks like I have set up my `~/.ensorc` correctly:
```
.ENSORC

ORCA: /home/henrique/bin/orca
ORCA version: 4.2.1
GFN-xTB: /home/henrique/bin/xtb/bin
CREST: /home/henrique/bin/crest/crest

$ENDPROGRAMS
```

This is the directory where my orca binary lives but ENSO is not finding ORCA (and looks like it is still looking for Turbomole):
```
 henrique  ~  teste_nmt  enso  python3 enso.py --checkinput
enso.py:3174: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if args.basisS != "def2-TZVP" and args.funcS is not 'pbeh-3c':
enso.py:3417: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if returncode is not 0:
enso.py:3503: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if returncode is not 0:
enso.py:3643: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if returncode is not 0:
enso.py:4670: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if returncode is not 0:

     __________________________________________________
    |                                                  |
    |                                                  |
    |                       ENSO -                     |
    |          energetic sorting of CREST CRE          |
    |          for automated NMR calculations          |
    |             University of Bonn, MCTC             |
    |                    July 2018                     |
    |                   version 2.0.1                  |
    |  F. Bohle, K. Schmitz, J. Pisarek and S. Grimme  |
    |                                                  |
    |__________________________________________________|
    
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


.ensorc is taken from: /home/henrique/teste_nmt/enso/.ensorc
Reading information from .ensorc.
Reading information from flags.dat.

ERROR: Can not convert resonance frequency: 'None' into float! Options are ['MHz number of your experimental spectrometer setup'].

WARNING: Can not convert resonance frequency! Flag -mf has to be set while executing the anmr program.
Using conformers from file /home/henrique/teste_nmt/enso/crest_conformers.xyz.

-----------------------------------------------------------
 PARAMETERS
-----------------------------------------------------------

number of atoms in system:                                     19
number of conformers:                                          119
charge:                                                        0
unpaired:                                                      0
solvent:                                                       chcl3
program for part1 and part2:                                   tm
program for part3:                                             tm
program for part4:                                             tm
using ANCOPT implemented in xTB for the optimization:          on
program for RRHO in part2 and part3:                           xtb
GFN version for RRHO and/or GBSA_Gsolv in part2 and 3:         gfn2
temperature:                                                   298.15
part1:                                                         on
part2:                                                         on
part3:                                                         on
part4:                                                         on
only boltzmann population:                                     off
calculate backup conformers:                                   off
functional for part1 and part2:                                pbeh-3c
functional for part3:                                          pw6b95
basis set for part3:                                           def2-TZVPP
calculate couplings:                                           on
functional for coupling calculation:                           pbe0
basis set for coupling calculation:                            def2-TZVP
calculate shieldings:                                          on
functional for shielding calculation:                          pbe0
basis set for shielding calculation:                           def2-TZVP
threshold for part1:                                           6.0
threshold for part2:                                           2.0
solvent model for part1 and part2:                             dcosmors
solvent model for Gsolv contribution of part2:                 sm
solvent model for part3:                                       dcosmors
solvent model for part4:                                       dcosmors
cautious checking for error and failed calculations:           on
checking the DFT-ensemble using CREST:                         off
maxthreads:                                                    1
omp:                                                           1
calculating spectra for:                                       1H
reference for 1H:                                              TMS
resonance frequency:                                           None
END of parameters


-----------------------------------------------------------
 PATHS of employed QM programs
-----------------------------------------------------------

The following program paths are used:
    xTB:          /home/henrique/bin/xtb/bin
    CREST:        /home/henrique/bin/crest/crest
Traceback (most recent call last):
  File "enso.py", line 12231, in <module>
    main(argv=None)
  File "enso.py", line 12138, in main
    ) = enso_startup(cwd,argv)
  File "enso.py", line 9287, in enso_startup
    error_logical = input_object.processQMpaths(args, error_logical)
  File "enso.py", line 8367, in processQMpaths
    print('    TURBOMOLE:    {}'.format(os.path.dirname(tmpath)))
  File "/usr/lib64/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by fabothch** [comment]
Hi,

for now, just use the orca path to your binary:
`ORCA: /home/henrique/bin/` as your ORCA path.
And the reason ENSO is searching for TURBOMOLE is because you apparently requested it (either in your .ensorc of flags.dat)
```
program for part1 and part2:                                   tm
program for part3:                                             tm
program for part4:                                             tm
```
I will update the code concerning the ORCA path to make it consistent to the other programs!

best,

fabothch
